-- Author      : gokulram.krishnan
-- Repository  : https://github.com/gokulramkrishnan/Useful-Jupyter-Notebook
-- Generated   : 2026-04-03

-- Satellite model: SAT_PRODUCT_PRODUCT
-- Entity: PRODUCT | Source: SRC_PRODUCT
-- Generated by gokulram.krishnan (datavault4dbt aligned)
{{ config(
    materialized='incremental',
    unique_key=['PRODUCT_HK', 'LOAD_DATE'],
    tags=['raw_vault','satellite']
) }}

{{- datavault4dbt.sat(
    src_pk='PRODUCT_HK',
    src_hashdiff={
        'is_hashdiff': true,
        'columns': [
          'PRODUCT_NAME
        - CATEGORY
        - UNIT_PRICE
        - IS_ACTIVE'
        ]
    },
    src_payload=[
      'PRODUCT_NAME
      - CATEGORY
      - UNIT_PRICE
      - IS_ACTIVE'
    ],
    src_ldts='LOAD_DATE',
    src_source='RECORD_SOURCE',
    source_model='stg_src_product'
) -}}
