-- Author      : gokulram.krishnan
-- Repository  : https://github.com/gokulramkrishnan/Useful-Jupyter-Notebook
-- Generated   : 2026-04-03

-- Satellite model: SAT_ORDER_ORDER
-- Entity: ORDER | Source: SRC_ORDER
-- Generated by gokulram.krishnan (datavault4dbt aligned)
{{ config(
    materialized='incremental',
    unique_key=['ORDER_HK', 'LOAD_DATE'],
    tags=['raw_vault','satellite']
) }}

{{- datavault4dbt.sat(
    src_pk='ORDER_HK',
    src_hashdiff={
        'is_hashdiff': true,
        'columns': [
          'ORDER_DATE
        - ORDER_AMOUNT
        - STATUS'
        ]
    },
    src_payload=[
      'ORDER_DATE
      - ORDER_AMOUNT
      - STATUS'
    ],
    src_ldts='LOAD_DATE',
    src_source='RECORD_SOURCE',
    source_model='stg_src_order'
) -}}
