-- Author      : gokulram.krishnan
-- Repository  : https://github.com/gokulramkrishnan/Useful-Jupyter-Notebook
-- Generated   : 2026-04-03

-- Satellite model: SAT_DIM_CUSTOMER_TGT_DIM_CUSTOMER
-- Entity: DIM_CUSTOMER | Source: TGT_DIM_CUSTOMER
-- Generated by gokulram.krishnan (datavault4dbt aligned)
{{ config(
    materialized='incremental',
    unique_key=['DIM_CUSTOMER_HK', 'LOAD_DATE'],
    tags=['raw_vault','satellite']
) }}

{{- datavault4dbt.sat(
    src_pk='DIM_CUSTOMER_HK',
    src_hashdiff={
        'is_hashdiff': true,
        'columns': [
          'CUSTOMER_HK
        - CUSTOMER_BK
        - FULL_NAME
        - EMAIL'
        ]
    },
    src_payload=[
      'CUSTOMER_HK
      - CUSTOMER_BK
      - FULL_NAME
      - EMAIL'
    ],
    src_ldts='LOAD_DATE',
    src_source='RECORD_SOURCE',
    source_model='stg_tgt_dim_customer'
) -}}
