-- Author      : gokulram.krishnan
-- Repository  : https://github.com/gokulramkrishnan/Useful-Jupyter-Notebook
-- Generated   : 2026-04-03

-- Satellite model: SAT_CUSTOMER_CUSTOMER
-- Entity: CUSTOMER | Source: SRC_CUSTOMER
-- Generated by gokulram.krishnan (datavault4dbt aligned)
{{ config(
    materialized='incremental',
    unique_key=['CUSTOMER_HK', 'LOAD_DATE'],
    tags=['raw_vault','satellite']
) }}

{{- datavault4dbt.sat(
    src_pk='CUSTOMER_HK',
    src_hashdiff={
        'is_hashdiff': true,
        'columns': [
          'FIRST_NAME
        - LAST_NAME
        - EMAIL
        - PHONE
        - CREATED_DATE'
        ]
    },
    src_payload=[
      'FIRST_NAME
      - LAST_NAME
      - EMAIL
      - PHONE
      - CREATED_DATE'
    ],
    src_ldts='LOAD_DATE',
    src_source='RECORD_SOURCE',
    source_model='stg_src_customer'
) -}}
