-- Author      : gokulram.krishnan
-- Repository  : https://github.com/gokulramkrishnan/Useful-Jupyter-Notebook
-- Generated   : 2026-04-03

-- Staging model: stg_tgt_dim_customer
-- Source: TGT_DIM_CUSTOMER
-- Generated by gokulram.krishnan (datavault4dbt aligned)
{{ config(materialized='view', tags=['staging']) }}

WITH source AS (
    SELECT
        CUSTOMER_HK,
    CUSTOMER_BK,
    FULL_NAME,
    EMAIL,
    COUNTRY_CODE,
    LOAD_DATE,
    RECORD_SOURCE,
        CURRENT_TIMESTAMP()                        AS LOAD_DATE,
        '{{ var("record_source") }}'           AS RECORD_SOURCE
    FROM {{ source('tgt_dim_customer_src', 'TGT_DIM_CUSTOMER') }}
),

hashed AS (
    SELECT
        MD5(CAST(COUNTRY_CODE AS VARCHAR))                     AS DIM_CUSTOMER_HK,
        *
    FROM source
)

SELECT * FROM hashed
