-- Author      : gokulram.krishnan
-- Repository  : https://github.com/gokulramkrishnan/Useful-Jupyter-Notebook
-- Generated   : 2026-04-03

-- Staging model: stg_src_customer
-- Source: SRC_CUSTOMER
-- Generated by gokulram.krishnan (datavault4dbt aligned)
{{ config(materialized='view', tags=['staging']) }}

WITH source AS (
    SELECT
        CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE,
    CREATED_DATE,
        CURRENT_TIMESTAMP()                        AS LOAD_DATE,
        '{{ var("record_source") }}'           AS RECORD_SOURCE
    FROM {{ source('src_customer_src', 'SRC_CUSTOMER') }}
),

hashed AS (
    SELECT
        MD5(CAST(CUSTOMER_ID AS VARCHAR))                     AS CUSTOMER_HK,
        *
    FROM source
)

SELECT * FROM hashed
