-- Author      : gokulram.krishnan
-- Repository  : https://github.com/gokulramkrishnan/Useful-Jupyter-Notebook
-- Generated   : 2026-04-03

-- Staging model: stg_src_product
-- Source: SRC_PRODUCT
-- Generated by gokulram.krishnan (datavault4dbt aligned)
{{ config(materialized='view', tags=['staging']) }}

WITH source AS (
    SELECT
        PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    UNIT_PRICE,
    IS_ACTIVE,
        CURRENT_TIMESTAMP()                        AS LOAD_DATE,
        '{{ var("record_source") }}'           AS RECORD_SOURCE
    FROM {{ source('src_product_src', 'SRC_PRODUCT') }}
),

hashed AS (
    SELECT
        MD5(CAST(PRODUCT_ID AS VARCHAR))                     AS PRODUCT_HK,
        *
    FROM source
)

SELECT * FROM hashed
