-- Author      : gokulram.krishnan
-- Repository  : https://github.com/gokulramkrishnan/Useful-Jupyter-Notebook
-- Generated   : 2026-04-03

-- Staging model: stg_src_order
-- Source: SRC_ORDER
-- Generated by gokulram.krishnan (datavault4dbt aligned)
{{ config(materialized='view', tags=['staging']) }}

WITH source AS (
    SELECT
        ORDER_ID,
    CUSTOMER_ID,
    PRODUCT_ID,
    ORDER_DATE,
    ORDER_AMOUNT,
    STATUS,
        CURRENT_TIMESTAMP()                        AS LOAD_DATE,
        '{{ var("record_source") }}'           AS RECORD_SOURCE
    FROM {{ source('src_order_src', 'SRC_ORDER') }}
),

hashed AS (
    SELECT
        MD5(CAST(ORDER_ID AS VARCHAR)||'||'||CAST(CUSTOMER_ID AS VARCHAR)||'||'||CAST(PRODUCT_ID AS VARCHAR))                     AS ORDER_HK,
        *
    FROM source
)

SELECT * FROM hashed
