# =============================================================================
# Author      : gokulram.krishnan
# Repository  : https://github.com/gokulramkrishnan/Useful-Jupyter-Notebook
# Description : """
# =============================================================================
"""
Agent 4: DBT Project Generator
Generates a complete dbt project using datavault4dbt v1.17.0 macros for Snowflake.
Produces: dbt_project.yml, packages.yml, profiles.yml, staging models,
raw vault models (hub/link/sat), schema.yml files with tests.

References:
  - datavault4dbt: github.com/ScalefreeCOM/datavault4dbt
  - datavault4dbt Snowflake docs
"""

import os
import json
import yaml
from pathlib import Path
from typing import Optional


# ─────────────────────────────────────────────────────────────────────────────
# Standalone file generators
# ─────────────────────────────────────────────────────────────────────────────

def generate_packages_yml(output_dir: str, datavault4dbt_version: str):
    content = f"""packages:
  - package: ScalefreeCOM/datavault4dbt
    version: {datavault4dbt_version}
"""
    _write(f"{output_dir}/packages.yml", content)


def generate_dbt_project_yml(
    output_dir: str, project_name: str, profile_name: str,
    schema_raw: str, schema_biz: str, schema_stg: str,
    hash_algorithm: str, load_date_col: str, record_source: str,
):
    content = f"""name: '{project_name}'
version: '1.0.0'
config-version: 2

profile: '{profile_name}'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

# ── datavault4dbt global variables ──────────────────────────────────────────
vars:
  # Hash algorithm: MD5 or SHA-256
  datavault4dbt:
    hash:                  '{hash_algorithm}'
    # Technical column names
    load_datetime:         '{load_date_col}'
    record_source:         'RECORD_SOURCE'
    # Snowflake-specific
    beginning_of_all_times: '1970-01-01 00:00:00.000'
    end_of_all_times:        '8888-12-31 23:59:59.999'
    # Ghost record defaults
    ghost_pk:              '0000000000000000000000000000000000000000'
    ghost_date:            '1970-01-01 00:00:00.000'
    ghost_rsrc:            'SYSTEM'
    is_incremental:        true

models:
  {project_name}:
    staging:
      +schema:       '{schema_stg}'
      +materialized: view
      +tags:         ['staging']

    raw_vault:
      +schema:       '{schema_raw}'
      +materialized: incremental
      +unique_key:   'dummy'          # overridden per model
      +tags:         ['raw_vault']
      hubs:
        +tags: ['hub']
      links:
        +tags: ['link']
      satellites:
        +tags: ['satellite']

    business_vault:
      +schema:       '{schema_biz}'
      +materialized: table
      +tags:         ['business_vault']
"""
    _write(f"{output_dir}/dbt_project.yml", content)


def generate_profiles_yml(output_dir: str, profile_name: str, target_database: str):
    content = f"""# profiles.yml — copy to ~/.dbt/profiles.yml and fill in credentials
{profile_name}:
  target: dev
  outputs:
    dev:
      type: snowflake
      account:   YOUR_SNOWFLAKE_ACCOUNT      # e.g. xy12345.us-east-1
      user:      YOUR_SNOWFLAKE_USER
      password:  YOUR_SNOWFLAKE_PASSWORD     # or use authenticator: externalbrowser
      role:      YOUR_SNOWFLAKE_ROLE
      database:  {target_database}
      warehouse: YOUR_SNOWFLAKE_WAREHOUSE
      schema:    DEV
      threads:   8
      client_session_keep_alive: false
      query_tag: dbt_{profile_name}

    prod:
      type: snowflake
      account:   YOUR_SNOWFLAKE_ACCOUNT
      user:      YOUR_SNOWFLAKE_USER
      password:  YOUR_SNOWFLAKE_PASSWORD
      role:      YOUR_SNOWFLAKE_ROLE
      database:  {target_database}
      warehouse: YOUR_SNOWFLAKE_WAREHOUSE
      schema:    PROD
      threads:   16
      client_session_keep_alive: false
      query_tag: dbt_{profile_name}
"""
    _write(f"{output_dir}/profiles.yml", content)


def generate_staging_model(output_dir: str, source_table: str, columns: list,
                            bk_columns: list, load_date_col: str, hash_algorithm: str,
                            entity: str, hash_key_col: str) -> str:
    """Generate a staging model SQL using datavault4dbt staging macro."""
    model_name = f"stg_{source_table.lower()}"
    col_list   = ",\n    ".join([f"{c['name']}" for c in columns])
    hash_fn    = "MD5" if hash_algorithm == "MD5" else "SHA2"
    bk_concat  = "||'||'||".join([f"CAST({bk} AS VARCHAR)" for bk in bk_columns])

    content = f"""-- Staging model: {model_name}
-- Source: {source_table}
-- Generated by gokulram.krishnan (datavault4dbt aligned)
{{{{ config(materialized='view', tags=['staging']) }}}}

WITH source AS (
    SELECT
        {col_list},
        CURRENT_TIMESTAMP()                        AS {load_date_col},
        '{{{{ var("record_source") }}}}'           AS RECORD_SOURCE
    FROM {{{{ source('{source_table.lower()}_src', '{source_table}') }}}}
),

hashed AS (
    SELECT
        {hash_fn}({bk_concat})                     AS {hash_key_col},
        *
    FROM source
)

SELECT * FROM hashed
"""
    path = f"{output_dir}/models/staging/{model_name}.sql"
    _write(path, content)
    return model_name


def generate_hub_model(output_dir: str, hub: dict) -> str:
    """Generate Hub model using datavault4dbt hub macro."""
    model_name  = hub["hub_name"].lower()
    dv4         = hub["dv4dbt"]
    src_bk_yaml = "\n      - ".join(dv4["src_bk"])

    content = f"""-- Hub model: {hub['hub_name']}
-- Entity: {hub['entity']}
-- Generated by gokulram.krishnan (datavault4dbt aligned)
{{{{ config(
    materialized='incremental',
    unique_key='{dv4["src_pk"]}',
    tags=['raw_vault','hub']
) }}}}

{{{{- datavault4dbt.hub(
    src_pk='{dv4["src_pk"]}',
    src_bk=[
      '{src_bk_yaml}'
    ],
    src_ldts='{dv4["src_ldts"]}',
    src_source='{dv4["src_source"]}',
    source_model='{dv4["source_model"]}'
) -}}}}
"""
    path = f"{output_dir}/models/raw_vault/hubs/{model_name}.sql"
    os.makedirs(os.path.dirname(path), exist_ok=True)
    _write(path, content)
    return model_name


def generate_link_model(output_dir: str, link: dict) -> str:
    """Generate Link model using datavault4dbt link macro."""
    model_name = link["link_name"].lower()
    dv4        = link["dv4dbt"]
    fk_yaml    = "\n      - ".join(dv4["src_fk"])
    src_models = dv4["source_model"] if isinstance(dv4["source_model"], list) else [dv4["source_model"]]
    src_model_yaml = "\n      - ".join(src_models)

    content = f"""-- Link model: {link['link_name']}
-- Entities: {link['entity_a']} <-> {link['entity_b']}
-- Generated by gokulram.krishnan (datavault4dbt aligned)
{{{{ config(
    materialized='incremental',
    unique_key='{dv4["src_pk"]}',
    tags=['raw_vault','link']
) }}}}

{{{{- datavault4dbt.link(
    src_pk='{dv4["src_pk"]}',
    src_fk=[
      '{fk_yaml}'
    ],
    src_ldts='{dv4["src_ldts"]}',
    src_source='{dv4["src_source"]}',
    source_model=[
      '{src_model_yaml}'
    ]
) -}}}}
"""
    path = f"{output_dir}/models/raw_vault/links/{model_name}.sql"
    os.makedirs(os.path.dirname(path), exist_ok=True)
    _write(path, content)
    return model_name


def generate_satellite_model(output_dir: str, sat: dict) -> str:
    """Generate Satellite model using datavault4dbt sat macro."""
    model_name  = sat["sat_name"].lower()
    dv4         = sat["dv4dbt"]
    payload_yaml = "\n      - ".join(dv4["src_payload"])
    hd_cols_yaml = "\n        - ".join(dv4["src_hashdiff"]["columns"])

    content = f"""-- Satellite model: {sat['sat_name']}
-- Entity: {sat['entity']} | Source: {sat['source_table']}
-- Generated by gokulram.krishnan (datavault4dbt aligned)
{{{{ config(
    materialized='incremental',
    unique_key=['{dv4["src_pk"]}', '{dv4["src_ldts"]}'],
    tags=['raw_vault','satellite']
) }}}}

{{{{- datavault4dbt.sat(
    src_pk='{dv4["src_pk"]}',
    src_hashdiff={{
        'is_hashdiff': true,
        'columns': [
          '{hd_cols_yaml}'
        ]
    }},
    src_payload=[
      '{payload_yaml}'
    ],
    src_ldts='{dv4["src_ldts"]}',
    src_source='{dv4["src_source"]}',
    source_model='{dv4["source_model"]}'
) -}}}}
"""
    path = f"{output_dir}/models/raw_vault/satellites/{model_name}.sql"
    os.makedirs(os.path.dirname(path), exist_ok=True)
    _write(path, content)
    return model_name


def generate_sources_yml(output_dir: str, metadata: dict):
    """Generate sources.yml for all source tables."""
    sources_block = {"version": 2, "sources": []}
    for src in metadata.get("sources", []):
        table = src.get("table_name","")
        sources_block["sources"].append({
            "name":     f"{table.lower()}_src",
            "database": "SOURCE_DB",    # replace with actual source DB
            "schema":   src.get("schema","OPERATIONAL"),
            "tables":   [{"name": table}],
        })
    path = f"{output_dir}/models/staging/sources.yml"
    _write(path, yaml.dump(sources_block, default_flow_style=False, sort_keys=False))


def generate_schema_yml(output_dir: str, dv_model: dict):
    """Generate schema.yml with column-level tests for hubs, links, satellites."""
    schema = {"version": 2, "models": []}

    for hub in dv_model.get("hubs", []):
        schema["models"].append({
            "name":        hub["hub_name"].lower(),
            "description": f"Hub for {hub['entity']} entity",
            "columns": [
                {"name": hub["hash_key"],
                 "description": "Hash key (primary key)",
                 "tests": ["unique", "not_null"]},
                *[{"name": bk, "tests": ["not_null"]} for bk in hub["business_keys"]],
                {"name": hub["ldts"],   "tests": ["not_null"]},
                {"name": hub["rsrc"],   "tests": ["not_null"]},
            ]
        })

    for link in dv_model.get("links", []):
        schema["models"].append({
            "name":        link["link_name"].lower(),
            "description": f"Link between {link['entity_a']} and {link['entity_b']}",
            "columns": [
                {"name": link["hash_key"],   "tests": ["unique","not_null"]},
                {"name": link["hub_a_hk"],   "tests": ["not_null"]},
                {"name": link["hub_b_hk"],   "tests": ["not_null"]},
                {"name": link["ldts"],       "tests": ["not_null"]},
            ]
        })

    for sat in dv_model.get("satellites", []):
        schema["models"].append({
            "name":        sat["sat_name"].lower(),
            "description": f"Satellite for {sat['entity']} from {sat['source_table']}",
            "columns": [
                {"name": sat["hub_hash_key"], "tests": ["not_null"]},
                {"name": sat["hashdiff"],     "tests": ["not_null"]},
                {"name": sat["ldts"],         "tests": ["not_null"]},
            ]
        })

    path = f"{output_dir}/models/raw_vault/schema.yml"
    _write(path, yaml.dump(schema, default_flow_style=False, sort_keys=False))


def generate_readme(output_dir: str, project_name: str, dv_model: dict,
                    datavault4dbt_version: str):
    content = f"""# {project_name}
Auto-generated dbt Data Vault 2.0 project using datavault4dbt v{datavault4dbt_version}.

## Setup
```bash
pip install dbt-snowflake
cp profiles.yml ~/.dbt/profiles.yml   # fill in credentials
dbt deps                               # install datavault4dbt
dbt run --select staging               # run staging models
dbt run --select raw_vault             # run raw vault
dbt test                               # run all tests
```

## Structure
```
models/
  staging/          — view models, hashing + technical columns
  raw_vault/
    hubs/           — {len(dv_model.get("hubs",[]))} Hub(s): {", ".join(h["hub_name"] for h in dv_model.get("hubs",[]))}
    links/          — {len(dv_model.get("links",[]))} Link(s): {", ".join(l["link_name"] for l in dv_model.get("links",[]))}
    satellites/     — {len(dv_model.get("satellites",[]))} Satellite(s)
  business_vault/   — add your Business Vault models here
```

## datavault4dbt global variables (dbt_project.yml)
| Variable | Value |
|---|---|
| hash | {dv_model.get("hash_algorithm","MD5")} |
| load_datetime | {dv_model.get("load_date_col","LOAD_DATE")} |
| record_source | RECORD_SOURCE |
"""
    _write(f"{output_dir}/README.md", content)


def _write(path: str, content: str):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)


# ─────────────────────────────────────────────────────────────────────────────
# Agent class
# ─────────────────────────────────────────────────────────────────────────────

class DBTGeneratorAgent:
    def run(self, metadata: dict, sttm: dict, dv_model: dict,
            output_dir: str, project_name: str, profile_name: str,
            target_database: str, schema_raw: str, schema_biz: str,
            schema_stg: str, datavault4dbt_version: str,
            hash_algorithm: str, record_source: str, load_date_col: str) -> dict:

        print("  Generating dbt project structure...")

        # ── Project config files ──────────────────────────────────────────────
        generate_packages_yml(output_dir, datavault4dbt_version)
        generate_dbt_project_yml(output_dir, project_name, profile_name,
                                  schema_raw, schema_biz, schema_stg,
                                  hash_algorithm, load_date_col, record_source)
        generate_profiles_yml(output_dir, profile_name, target_database)
        generate_sources_yml(output_dir, metadata)
        print("    ✅ dbt_project.yml, packages.yml, profiles.yml, sources.yml")

        # ── Staging models ────────────────────────────────────────────────────
        from agents.agent_data_vault import infer_business_keys, infer_entity_name, hash_key_col
        bk_map = infer_business_keys(metadata.get("sources",[]))
        staging_models = []
        for src in metadata.get("sources",[]):
            table   = src.get("table_name","")
            entity  = infer_entity_name(table)
            hk_col  = hash_key_col(entity)
            bk_cols = bk_map.get(table,[])
            m = generate_staging_model(
                output_dir, table, src.get("columns",[]),
                bk_cols, load_date_col, hash_algorithm, entity, hk_col
            )
            staging_models.append(m)
        print(f"    ✅ {len(staging_models)} staging model(s)")

        # ── Raw Vault models ──────────────────────────────────────────────────
        hub_models  = [generate_hub_model(output_dir, h) for h in dv_model.get("hubs",[])]
        link_models = [generate_link_model(output_dir, l) for l in dv_model.get("links",[])]
        sat_models  = [generate_satellite_model(output_dir, s) for s in dv_model.get("satellites",[])]
        print(f"    ✅ {len(hub_models)} hub(s), {len(link_models)} link(s), {len(sat_models)} satellite(s)")

        # ── Schema + README ───────────────────────────────────────────────────
        generate_schema_yml(output_dir, dv_model)
        generate_readme(output_dir, project_name, dv_model, datavault4dbt_version)
        print("    ✅ schema.yml + README.md")

        return {
            "staging_models":   len(staging_models),
            "raw_vault_models": len(hub_models) + len(link_models) + len(sat_models),
            "schema_files":     1,
        }
