-- Author      : gokulram.krishnan
-- Repository  : https://github.com/gokulramkrishnan/Useful-Jupyter-Notebook
-- Generated   : 2026-04-03

-- Hub model: HUB_PRODUCT
-- Entity: PRODUCT
-- Generated by gokulram.krishnan (datavault4dbt aligned)
{{ config(
    materialized='incremental',
    unique_key='PRODUCT_HK',
    tags=['raw_vault','hub']
) }}

{{- datavault4dbt.hub(
    src_pk='PRODUCT_HK',
    src_bk=[
      'PRODUCT_ID'
    ],
    src_ldts='LOAD_DATE',
    src_source='RECORD_SOURCE',
    source_model='stg_src_product'
) -}}
