-- Author      : gokulram.krishnan
-- Repository  : https://github.com/gokulramkrishnan/Useful-Jupyter-Notebook
-- Generated   : 2026-04-03

-- Hub model: HUB_CUSTOMER
-- Entity: CUSTOMER
-- Generated by gokulram.krishnan (datavault4dbt aligned)
{{ config(
    materialized='incremental',
    unique_key='CUSTOMER_HK',
    tags=['raw_vault','hub']
) }}

{{- datavault4dbt.hub(
    src_pk='CUSTOMER_HK',
    src_bk=[
      'CUSTOMER_ID'
    ],
    src_ldts='LOAD_DATE',
    src_source='RECORD_SOURCE',
    source_model='stg_src_customer'
) -}}
