-- Author      : gokulram.krishnan
-- Repository  : https://github.com/gokulramkrishnan/Useful-Jupyter-Notebook
-- Generated   : 2026-04-03

-- Hub model: HUB_DIM_CUSTOMER
-- Entity: DIM_CUSTOMER
-- Generated by gokulram.krishnan (datavault4dbt aligned)
{{ config(
    materialized='incremental',
    unique_key='DIM_CUSTOMER_HK',
    tags=['raw_vault','hub']
) }}

{{- datavault4dbt.hub(
    src_pk='DIM_CUSTOMER_HK',
    src_bk=[
      'COUNTRY_CODE'
    ],
    src_ldts='LOAD_DATE',
    src_source='RECORD_SOURCE',
    source_model='stg_tgt_dim_customer'
) -}}
