-- Author      : gokulram.krishnan
-- Repository  : https://github.com/gokulramkrishnan/Useful-Jupyter-Notebook
-- Generated   : 2026-04-03

-- Hub model: HUB_ORDER
-- Entity: ORDER
-- Generated by gokulram.krishnan (datavault4dbt aligned)
{{ config(
    materialized='incremental',
    unique_key='ORDER_HK',
    tags=['raw_vault','hub']
) }}

{{- datavault4dbt.hub(
    src_pk='ORDER_HK',
    src_bk=[
      'ORDER_ID
      - CUSTOMER_ID
      - PRODUCT_ID'
    ],
    src_ldts='LOAD_DATE',
    src_source='RECORD_SOURCE',
    source_model='stg_src_order'
) -}}
