CREATE OR REPLACE VIEW V_CUSTOMER_ORDERS AS
SELECT
    c.CUSTOMER_ID,
    c.FIRST_NAME || ' ' || c.LAST_NAME  AS FULL_NAME,
    c.EMAIL,
    o.ORDER_ID,
    o.ORDER_DATE,
    o.ORDER_AMOUNT,
    o.STATUS,
    p.PRODUCT_NAME,
    p.CATEGORY
FROM       SRC_CUSTOMER  c
INNER JOIN SRC_ORDER     o  ON c.CUSTOMER_ID = o.CUSTOMER_ID
INNER JOIN SRC_PRODUCT   p  ON o.PRODUCT_ID  = p.PRODUCT_ID
WHERE      o.STATUS IN ('ACTIVE', 'SHIPPED')
  AND      o.ORDER_AMOUNT > 0;
