-- Sample SQL: Order processing ETL
-- gokulram.krishnan

CREATE TABLE SRC_ORDER (
    ORDER_ID     INTEGER      NOT NULL PRIMARY KEY,
    CUSTOMER_ID  INTEGER      NOT NULL,
    PRODUCT_ID   INTEGER      NOT NULL,
    ORDER_DATE   DATE         NOT NULL,
    ORDER_AMOUNT DECIMAL(18,2),
    STATUS       VARCHAR(50)
);

CREATE TABLE SRC_PRODUCT (
    PRODUCT_ID   INTEGER       NOT NULL PRIMARY KEY,
    PRODUCT_NAME VARCHAR(255)  NOT NULL,
    CATEGORY     VARCHAR(100),
    UNIT_PRICE   DECIMAL(18,2) NOT NULL
);

CREATE TABLE TGT_FACT_ORDER (
    ORDER_HK     VARCHAR(32)   NOT NULL PRIMARY KEY,
    CUSTOMER_HK  VARCHAR(32)   NOT NULL,
    PRODUCT_HK   VARCHAR(32)   NOT NULL,
    ORDER_DATE   DATE          NOT NULL,
    ORDER_AMOUNT DECIMAL(18,2),
    LOAD_DATE    TIMESTAMP     NOT NULL,
    RECORD_SOURCE VARCHAR(100) NOT NULL
);

INSERT INTO TGT_FACT_ORDER (ORDER_HK, CUSTOMER_HK, ORDER_DATE, ORDER_AMOUNT)
SELECT MD5(CAST(ORDER_ID AS VARCHAR)),
       MD5(CAST(CUSTOMER_ID AS VARCHAR)),
       ORDER_DATE,
       NVL(ORDER_AMOUNT, 0)
FROM   SRC_ORDER
WHERE  STATUS = 'ACTIVE';
