-- Author      : gokulram.krishnan
-- Repository  : https://github.com/gokulramkrishnan/Useful-Jupyter-Notebook
-- Generated   : 2026-04-03

-- Link model: LNK_CUSTOMER_ORDER
-- Entities: CUSTOMER <-> ORDER
-- Generated by gokulram.krishnan (datavault4dbt aligned)
{{ config(
    materialized='incremental',
    unique_key='LNK_CUSTOMER_ORDER_HK',
    tags=['raw_vault','link']
) }}

{{- datavault4dbt.link(
    src_pk='LNK_CUSTOMER_ORDER_HK',
    src_fk=[
      'CUSTOMER_HK
      - ORDER_HK'
    ],
    src_ldts='LOAD_DATE',
    src_source='RECORD_SOURCE',
    source_model=[
      'stg_src_customer
      - stg_src_order'
    ]
) -}}
