-- Author      : gokulram.krishnan
-- Repository  : https://github.com/gokulramkrishnan/Useful-Jupyter-Notebook
-- Generated   : 2026-04-03

-- Link model: LNK_ORDER_PRODUCT
-- Entities: ORDER <-> PRODUCT
-- Generated by gokulram.krishnan (datavault4dbt aligned)
{{ config(
    materialized='incremental',
    unique_key='LNK_ORDER_PRODUCT_HK',
    tags=['raw_vault','link']
) }}

{{- datavault4dbt.link(
    src_pk='LNK_ORDER_PRODUCT_HK',
    src_fk=[
      'ORDER_HK
      - PRODUCT_HK'
    ],
    src_ldts='LOAD_DATE',
    src_source='RECORD_SOURCE',
    source_model=[
      'stg_src_order
      - stg_src_product'
    ]
) -}}
